CREATE TABLE BLOCK(
BLOCK_ID VARCHAR2(20),
BLOCK_NAME VARCHAR2(20),
CONSTRAINT PKB PRIMARY KEY(BLOCK_ID));

CREATE TABLE CLASSROOM(
CLASSROOM_ID VARCHAR2(20),
HAS_PROJECTOR VARCHAR2(10),
BLOCK_ID VARCHAR2(20),
CONSTRAINT PKC PRIMARY KEY(CLASSROOM_ID),
CONSTRAINT FKC FOREIGN KEY(BLOCK_ID) REFERENCES  BLOCK(BLOCK_ID));


CREATE TABLE DEPARTMENT(
DEPT_ID VARCHAR2(20),
DEPT_NAME VARCHAR2(20),
CONSTRAINT PKD PRIMARY KEY (DEPT_ID));

CREATE TABLE FACULTY(
FACULTY_ID VARCHAR2(20),
FACULTY_NAME VARCHAR2(30),
EMAIL VARCHAR(255),
PH_NO NUMBER,
DEPT_ID VARCHAR2(20),
CONSTRAINT PKF PRIMARY KEY(FACULTY_ID),
CONSTRAINT FKF FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID));

CREATE TABLE SUBJECT(
SUB_CODE VARCHAR2(20),
SUB_NAME VARCHAR(255),
SUB_ABBREVATION VARCHAR2(20),
CONSTRAINT PKS PRIMARY KEY(SUB_CODE));


CREATE TABLE HANDLES(
SUB_CODE VARCHAR2(20),
FACULTY_ID VARCHAR2(20),
CONSTRAINT PKH PRIMARY KEY(SUB_CODE,FACULTY_ID),
CONSTRAINT FKH FOREIGN KEY(SUB_CODE) REFERENCES SUBJECT(SUB_CODE),
CONSTRAINT FKH2 FOREIGN KEY(FACULTY_ID) REFERENCES FACULTY(FACULTY_ID));

CREATE TABLE SECTION(
SEC_ID VARCHAR2(20),
SEC VARCHAR2(20),
SEM VARCHAR2(20),
ACADEMIC_YEAR NUMBER,
FACULTY_ID VARCHAR2(20),
CONSTRAINT PKSE PRIMARY KEY(SEC_ID),
CONSTRAINT FKSE FOREIGN KEY(FACULTY_ID) REFERENCES FACULTY(FACULTY_ID));


CREATE TABLE BATCH(
SEC_ID VARCHAR2(20),
BATCH_NAME VARCHAR2(20),
CONSTRAINT PKBA PRIMARY KEY(SEC_ID,BATCH_NAME),
CONSTRAINT FKBA FOREIGN KEY (SEC_ID) REFERENCES SECTION(SEC_ID));

CREATE TABLE CLASS_OR_LAB(
SUB_CODE VARCHAR2(20),
FACULTY_ID VARCHAR2(20),
DEPT_ID VARCHAR2(20),
CLASSROOM_ID VARCHAR2(20),
BLOCK_ID VARCHAR2(20),
SEC_ID VARCHAR2(20),
DAYY VARCHAR2(20),
TIMEE VARCHAR2(20),
DURATIONN VARCHAR2(20),
CONSTRAINT PKCL PRIMARY KEY (SUB_CODE,FACULTY_ID,DEPT_ID,CLASSROOM_ID,BLOCK_ID,SEC_ID,DAYY),
CONSTRAINT FKCL FOREIGN KEY(SUB_CODE) REFERENCES SUBJECT(SUB_CODE),
CONSTRAINT FKCL2 FOREIGN KEY(FACULTY_ID) REFERENCES FACULTY(FACULTY_ID),
CONSTRAINT FKCL3 FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID),
CONSTRAINT FKCL4 FOREIGN KEY(CLASSROOM_ID) REFERENCES CLASSROOM(CLASSROOM_ID),
CONSTRAINT FKCL5 FOREIGN KEY(BLOCK_ID) REFERENCES BLOCK(BLOCK_ID),
CONSTRAINT FKCL6 FOREIGN KEY(SEC_ID) REFERENCES SECTION(SEC_ID));











